# Generated by Django 3.2.7 on 2022-05-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('subtitle', models.CharField(default='', max_length=400)),
                ('isbn', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('pubdate', models.DateField()),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('desc_pub', models.TextField(blank=True)),
                ('desc_index', models.TextField(blank=True)),
                ('kdc', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('num_review', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('is_love', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('booka', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=400, null=True)),
                ('as_a', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_state', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='backend.book')),
            ],
        ),
    ]
