# Generated by Django 3.2.7 on 2022-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='banner',
            name='color2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
