# Generated by Django 3.2.7 on 2022-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220518_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='color3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
