# Generated by Django 3.2.7 on 2022-04-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc_index',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc_pub',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_love',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
